name: Build App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Login
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: BeneSim
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Compile
      run: |
        mkdir build
        docker container run --rm -v $(pwd):/app -w /app/build docker.pkg.github.com/benesim/beneoverlay/gcc-windows:latest -c "qmake .."
        docker container run --rm -v $(pwd):/app -w /app/build docker.pkg.github.com/benesim/beneoverlay/gcc-windows:latest -c make
        echo ${{ github.ref }}
    - name: Package
      run: |
        cd build
        zip BeneOverlay.zip BeneOverlay.exe
    - name: Archive Artifact
      uses: actions/upload-artifact@v1
      with:
        name: BeneOverlay
        path: build/BeneOverlay.zip
  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v1
      with:
        name: BeneOverlay
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: false
    - name: Upload Release Assets
      id: upload-release-asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./BeneOverlay/BeneOverlay.zip
        asset_name: BeneOverlay_x86-64-windows.zip
        asset_content_type: application/zip
